#pragma once

#define BLITZACTOR_FLAG_NONE		0
#define BLITZACTOR_FLAG_RADAR		1
#define BLITZACTOR_FLAG_BARRICADE	2
#define BLITZACTOR_FLAG_TREASURE	4

#define MBLITZ_CLASS_HUNTER			0
#define MBLITZ_CLASS_SLAUGHTERER	1
#define MBLITZ_CLASS_TRICKSTER		2
#define MBLITZ_CLASS_GLADIATOR		3
#define MBLITZ_CLASS_DUELIST		4
#define MBLITZ_CLASS_INCINERATOR	5
#define MBLITZ_CLASS_COMBATOFFICER	6
#define MBLITZ_CLASS_ASSASSIN		7
#define MBLITZ_CLASS_WRECKER		8
#define MBLITZ_CLASS_MAX			9

#define MBLITZ_SKILLTYPE_WEAPON		0
#define MBLITZ_SKILLTYPE_BULLET		1
#define MBLITZ_SKILLTYPE_ARMOR		2
#define MBLITZ_SKILLTYPE_BOMB		3
#define MBLITZ_SKILLTYPE_MAGAZINE	4
#define MBLITZ_SKILLTYPE_MEDIC		5
#define MBLITZ_SKILLTYPE_MAX		6

#define MBLITZ_SKILLGRADE_MAX		4

#define MBLITZ_SPAWN_BARRICADE		"spawn_blitz_barricade"
#define MBLITZ_SPAWN_RADAR			"spawn_blitz_radar"
#define MBLITZ_SPAWN_HONORITEM		"spawn_blitz_honoritem"
#define MBLITZ_SPAWN_GUARDIAN		"spawn_blitz_guardian"